### ISSUE TITLE
Free/Price values not validated in app

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#100]
Tested with Galaxy S8 and iPhone 7+

# Description of issues

**Scenario 1**
If you reverse the price values for an event on Contentful e.g. 20 in Event Price Low and 10 in Event Price High, the app doesn't recognise this and reports "From: £20" on the event thumbnail and just "£20" on the details page. 

See "Mr. Poopybutthole" for an example event. 

**Scenario 2**
If an event is marked as free, but prices values are set in the Low/High fields, then the event displays "From: £20" on the event thumbnail, but "Free" on the event details page.

I can potential for this happening by accident when a content editor is creating an event in Contentful due to the fact that the price fields have a scrolling function which they may inadvertently modify without realising. 

See "The Imp" for an example event.

**Scenario 3**
If an event is marked as not free but 0 is put for both prices it will display £0.

See "Sasha Velour" for an example event. 

# Expected Behaviour

**Scenario 1** - If "Price Low" is greater than "Price High" then the price values are swapped.

**Scenario 2** - If the event is marked as "Free", but a price value is added in one/both of the price fields, it is marked as free. This may require some discussion though. Perhaps some validation could be added, so that if "Free" is set to yes, the price low/high fields _have_ to be 0 to publish changes. 

**Scenario 3** - If there is not a value greater than 0 in the price fields, the event is marked as free.

# Steps to reproduce

- Open one of the example events (Mr. Poopybutthole / The Imp / Sasha Velour)

# Screenshots

**Scenario 1**
<img width=400 src="https://user-images.githubusercontent.com/33623842/38991956-2b43b1d0-43d7-11e8-9917-99bcc34d2675.jpg">
<img width=400 src="https://user-images.githubusercontent.com/33623842/38991891-fcb29520-43d6-11e8-9c7c-1366ca7a7305.jpg">

**Scenario 2**
<img width=400 src="https://user-images.githubusercontent.com/33623842/39138581-2c8597d6-4718-11e8-9648-f40caf342d20.jpg">
<img width=400 src="https://user-images.githubusercontent.com/33623842/39138584-2f7f4428-4718-11e8-80e6-25d0690c3c5f.jpg">

**Scenario 3**
<img width=400 src="https://user-images.githubusercontent.com/33623842/38991973-383ed6bc-43d7-11e8-86a0-1daae20011c1.jpg">
<img width=400 src="https://user-images.githubusercontent.com/33623842/38991983-3f000476-43d7-11e8-87aa-c6320ed976e5.jpg">

**Comment by lani-s** [comment]
See also: https://github.com/redbadger/pride-london-app/issues/102

**Comment by zoeabryant** [comment]
@declanslevin  What is the expected behaviour for this issue?
Should we:

1. Reverse price listings if the 'High' price is lower than the 'Low' price
2. Ignore 'High' and 'Low' pricing if the event is marked as 'Free'
3. If 'High' and 'Low' pricing are both '£0' the event should be treated as if it is marked 'Free'

**Comment by declanslevin** [comment]
@zoeabryant Correct

**Comment by declanslevin** [comment]
Fixed
