### ISSUE TITLE
Events with a single ticket price and Free events show "From: £x" 

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#102]
Tested on Samsung S8 (Android 8.0) + iPhone 7+ (iOS 10.3.1) 

On a single ticket price event's page, the price shows "From: £x" - It should probably just say something like "Price: £x" for these events.

On free event pages, the price shows "From: £0" - It should probably just say something like "Free event".

This would make the behaviour more consistent with the price overlays on the event listing page. 

An example event with a single ticket price is "Noob Noob" or "Tiny Rick".

**Comment by declanslevin** [comment]
This is actually debatably a bug, because if you set the event as Free, but enter values besides 0 in the low/high event price fields, the event will report "Free" on the event thumbnail, but on the page itself it will show price as "From: £x"

E.g.
![20180408_135717](https://user-images.githubusercontent.com/33623842/38467769-0fe2fc3e-3b35-11e8-8ad2-c58c959ed57d.jpg)
![20180408_135822](https://user-images.githubusercontent.com/33623842/38467771-17573e76-3b35-11e8-970e-b92e1a62c60a.jpg)

**Comment by lani-s** [comment]
See also https://github.com/redbadger/pride-london-app/issues/100

**Comment by declanslevin** [comment]
Looks like this has been resolved as part of the Event details page work, closing
