### ISSUE TITLE
Event description not being loaded for specific event on iOS 

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#104]
Tested on iPhone 7+ (iOS 10.3.1) and iPhone 6 (10.3.3)

This is a weird one - originally the event was appearing correctly when loaded, but in the past couple of days something appears to have happened which is causing this regression in behaviour. 

https://app.contentful.com/spaces/n2o4hgsv6wcx/entries/1Yo3rc8E6ooSOCoS846qmc

The event description for the above event is blank, except for the url linked image at the top of the event:
`![Pride in London](https://www.cityam.com/assets/uploads/main-image/cam_standard_article_main_image/london-supports-gay-pride-2017-809667286-5960b48f8609e.jpg)`

If I remove the image, it will actually load the content up to the point where the next image is linked:

> 👨‍❤️‍👨👩‍❤️‍👩👬👭🌈❤️💛💚💙💜🏳️‍🌈✝️☦️☪️🕉☸️✡️🔯🕎⚛️💒🎎🎶📣☺︎♨︎⚧♁♂⚣⚦⚭☭🃕🁒🂉❖❀⌘⌧⌕⎙⏂␆⏚⏞✉︎☠♿︎♼AÀÁÂÄÆÃÅĀBCÇĆČDEÈÉÊËĒĖĘFGHIÎÏÍĪĮÌJKLŁMNÑŃOÔÖÒÓŒØŌÕPQRSŚŠTUÛÜÙÚŪVWXYŸZŽŹŻ!@£$%^&*()_+_=-0987654321∑´®†œ¥¨^ø¨dƒaßƒƒ©˙∆˚µ~∫√ç≈Ω><.,:":":;'\][{}~`§±FFuuuuuuuuuuuuu
> ❤️💛💚💙💜
> ❤️💛💚💙💜
> ❤️💛💚💙💜
> ❤️💛💚💙💜
> ❤️💛💚💙💜
> ❤️💛💚💙💜
> ❤️💛💚💙💜

It seems like something funky is going on with the markdown and the way Contentful/the app interprets it? It suspect this might be the cause of the crash on Android as well: #103

It is most likely linked to #96 also.

**Comment by daralthus** [comment]
I believe this has been fixed in https://github.com/redbadger/pride-london-app/pull/150

**Comment by declanslevin** [comment]
Doesn't look like it is, it still only loads the url linked image

<img width=400 src="https://user-images.githubusercontent.com/33623842/39048020-fba37ff6-4493-11e8-893f-8c9ebe27be9c.PNG">

**Comment by RGBboy** [comment]
I merged a PR which likely mitigates this. Essentially we only expect editors to input paragraph content via contentful.

**Comment by declanslevin** [comment]
This is fixed
