### ISSUE TITLE
iOS doesn't allow swiping between tabs, Android does

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#105]
Tested on Samsung Galaxy S8 and iPhone 7+ 

Android allows you to navigate between tabs by swiping while iOS doesn't. 

Do we actually want swiping? It seems like it's not always enabled on Android apps. Or do we want to make iOS swipable like Android? 

Raising this as a consistency issue, probably one for the UXD lot to make a decision on ;)

**Comment by robbiemccorkell** [comment]
This was actually deliberate, since tab swiping is a platform interaction on Android, but not a thing on iOS. Definitely one for UX though, not for me to make that decision really.

**Comment by frigus02** [comment]
Actually I noticed on Android swiping is not common for bottom bars. It is definitely something for UX, though.
