### ISSUE TITLE
Home page "Featured events" list can't be directly refreshed

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#110]
Tested on Galaxy S8 (8.0) and iPhone 7+ (10.3.1)

It's not possible to refresh the Featured events list on the home page by dragging from top to bottom. even opening "View All" and attempting to refresh doesn't work. 

To trigger a refresh, you need to go to the Events tab and refresh there. 

To reproduce:
- Open the app and take note of the featured events on the home page
- Make a change to the Feature events list on Contentful (add/remove events, make sure the changes appear in the top 6 items in the list)
- Drag down from the top of the page
> It doesn't refresh
- Open View All and drag down from the top of the page
> It doesn't refresh
- Hit Back, switch to the Events tab and refresh page
- Switch back to Home tab
> Featured events have been updated

It is possible to refresh, it's just a bit awkward so logging this an enhancement.

**Comment by kristofhamilton** [comment]
Makes sense to have pull to refresh on the home too if possible.

**Comment by RGBboy** [comment]
We will cover this as part of https://trello.com/c/VLDK9GUW/196-refreshing-content
