### ISSUE TITLE
Entire name of events with very long titles are displayed on the home page, which distorts the layout of the events

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#111]
Tested on multiple devices:
Galaxy S8, Galaxy Note Edge, iPhone 7+, iPhone 6, iPhone X (BrowserStack) 

The entire name of events with very long titles get displayed on the home page when the event is added to the Featured events list. This disrupts the layout of the featured events and they become misaligned, leaving large sections of whitespace:

<img width=400 src="https://user-images.githubusercontent.com/33623842/38501866-e213f084-3c05-11e8-95d1-dc8c38fd7233.jpg">

**Comment by RGBboy** [comment]
Would love to get UI to chime in here. We can probably truncate after a certain size. Would love to know how many lines should we allow? One? Two? More?

**Comment by RGBboy** [comment]
Two lines has been decided 😀
