### ISSUE TITLE
Events can be added multiple times to the "Featured Events" list

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#112]
Tested on Galaxy S8, iPhone 7+

It is possible to add an event multiple times to the Featured Events list on Contentful. This event is then displayed multiple times in the app (when the View all button is tapped):
<img width=400 src="https://user-images.githubusercontent.com/33623842/38503270-88cbc610-3c09-11e8-8a64-1997e533a1ea.jpg">

It might not be immediately obvious to the content editor, as they won't be added to the home page unless the list is reordered so that the duplicated events are added to the first 6 items. But this is possible to do:
<img width=400 src="https://user-images.githubusercontent.com/33623842/38503514-2bfb28e4-3c0a-11e8-9e35-98d960574ce7.jpg">

**Comment by RGBboy** [comment]
This issue should now be fixed. @declanslevin close this what you are happy.

**Comment by declanslevin** [comment]
Tested on 
Galaxy S8
Galaxy S7
iPhone X
iPhone 8
iPhone 7+
iPhone 6

Looks good, closing
