### ISSUE TITLE
Remove timezone from Contentful

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#114]
## Description of issue

https://trello.com/c/g6DM173E/131-contentful-event-times

## Expected behaviour

user sees event time in BST

## Steps to reproduce

List the exact steps you took to arrive at the issue.

## OS / Browser / Device model

List all the devices and browsers effected, with specific version numbers.

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by RGBboy** [comment]
Closing as we have created a new trello ticket to cover this. https://trello.com/c/wVJtGpjs/197-handling-timezones
