### ISSUE TITLE
The date and time filters allow you to end up with an empty events page

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#118]
## Description of issue

If you change the date filter to a range of dates where there are no listed events, you are able to click "Show 0 events" and end up on an empty events page. 
The above also happens if you set the time filter so that there are no listed events.

## Expected behaviour

I would expect the date and time filters to behave the same way as the Category filter and disable the "Show x events" button until a valid range/time is selected. At the very least it should show a message on the page along the lines of "There are no events that match your filter" instead of a blank page.

## Steps to reproduce

- Open the app and go to the events listing page
(at this stage it would be helpful to identify a range of dates that don't contain any events i.e. 1-5 May)
- Open the date filter and set the range to a range of dates without events
> The button will display "No events" 
- Tap the button
> You are taken to a page that is empty

## OS / Browser / Device model

Samsung Galaxy S8 (Android 8.0)

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/38735556-03056278-3f21-11e8-9146-13bde53d3d1d.jpg">

**Comment by JunBadger** [comment]
![img_8696](https://user-images.githubusercontent.com/14994865/39590098-d2a61032-4ef7-11e8-9dff-ee9f34275e76.JPG)

Button should appear inactive - same as inactive button in filter list

**Comment by RGBboy** [comment]
While I understand that we are trying our best to stop users seeing an empty event list page I think we should expect it to happen at some point and design accordingly. This is going to become more of an issue when we start hiding past events, especially in the featured event and curated event screens.

**Comment by clmntnbrn** [comment]
I agree with @declanslevin and @JunBadger that we should disable the button as per the pattern on the other filters 👍

**Comment by declanslevin** [comment]
We now have the empty events page placeholder so this can be closed.
