### ISSUE TITLE
Developer onboarding

### ISSUE THREAD

**Issue by markholland** [redbadger/pride-london-app#12]
Documentation for:
- Getting the project setup
- Running on emulators
- Requesting iOS device be added to list for running on a device (needs implementing)
- Running on Android device

**Comment by RGBboy** [comment]
If you would like to pair on this I'd be happy to. I'm a pair of fresh eyes which may help fill in any blanks.

**Comment by charypar** [comment]
I made some fixes in #54 and added basic contribution guidelines in #58

**Comment by RGBboy** [comment]
Added iOS local development in #82
