### ISSUE TITLE
Header is missing from the view all Featured events page

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#139]
## Description of issue

When you "View all" featured events, the header has gone missing, so there is no back button. Also on iPhone X it results in the top of the page being obscured by the speaker/camera bit. 

## Expected behaviour

There should be a page header with a back button and label "Featured events". It should match the styling from an Event's individual listing page. 

## Steps to reproduce

- From the home page, tap "View all" next to the Featured events header
> All featured events page is opened, page header is missing

## OS / Browser / Device model

Galaxy S8 (8.0) Physical
iPhone 7+ (10.3.1) Physical

iPhone X (11.0) BrowserStack

## Screenshots
Galaxy S8:
**Previous:**
<img width=400 src="https://user-images.githubusercontent.com/33623842/38861412-6c8ae766-422a-11e8-8553-44d88cb033f8.jpg">

**Current:**
<img width=400 src="https://user-images.githubusercontent.com/33623842/38861420-73212928-422a-11e8-9b63-1ad3003e19de.jpg">

iPhoneX:
**Previous:**
<img width="400" src="https://user-images.githubusercontent.com/33623842/38861567-c83fca90-422a-11e8-957c-94e9f92f5d1c.png">

**Current:**
<img width="410" src="https://user-images.githubusercontent.com/33623842/38861589-d3880afc-422a-11e8-8f92-38a14edd9440.png">

**Comment by RGBboy** [comment]
Fixed in #142
