### ISSUE TITLE
Tab bar should be hidden when individual Event listing is opened

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#140]
## Description of issue

The tab bar is visible when an individual event listing is opened, using up precious real estate. 

## Expected behaviour

When an individual event listing is opened the tab bar is collapsed/hidden. 
The same behaviour should apply when opening the "View all feature events" page. 

## Steps to reproduce

- Go to the Events tab and open an event

## OS / Browser / Device model

Galaxy S8
iPhone 7+ 

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/38862488-f845f7ee-422c-11e8-8954-c1a3518da10b.jpg">

**Comment by RGBboy** [comment]
Fixed in #142
