### ISSUE TITLE
It is possible to select past dates in the event date filter

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#146]
## Description of issue

There is a comment from Jun on https://trello.com/c/PQIdwgZb/125-ui-events-listing-filter-events-list-by-date that states the one of the ACs should be that "User won't be able to select a date before today", but the behaviour currently allows this. 

**Note:** This is also an A/C of https://trello.com/c/JVwbl10D/154-whole-app-not-showing-past-events. It has been added there as a development task to complete that ticket so who ever picks this up please advance that ticket when complete 👍  

## Expected behaviour

Should not be able to select dates before today. 

## Steps to reproduce

- Go to the Events page and open the date filter
- Select a date before today's date
> It is selectable

## OS / Browser / Device model

Galaxy S8
iPhone 7+

## Screenshots

As indicated by the dot, today's date is 18th April
<img width=400 src="https://user-images.githubusercontent.com/33623842/38926322-296b65b6-42fa-11e8-9c12-8a0e807f91df.jpg">

**Comment by JunBadger** [comment]
Covered in this story: https://trello.com/c/JVwbl10D/154-whole-app-not-showing-past-events

**Comment by JunBadger** [comment]
MVP could be to not be able to select any dates before the first event of Pride

**Comment by lani-s** [comment]
Should we design something for the empty events listing instead? Will need UXD

**Comment by robbiemccorkell** [comment]
On the other filter pages we just disable the submit button if the applied filter would result in 0 events. We could do that quite easily for the dates dialog. So if a user selects any date range where no events would appear the button underneath would be grey, disabled, and say "No events" like it does on the filter modal.

**Comment by RGBboy** [comment]
I think handling the no events case is still important. It will be applied in a number of places for example, event listing, curated events (e.g. favourite events) etc. Also would be used as a placeholder if the user fails to load the data from contentful on their first load.

**Comment by JunBadger** [comment]
Let's knock back past dates 50% opacity

**Comment by robbiemccorkell** [comment]
For now I've created the PR above. I've just faded the days, but they are still selectable. Let me know if I should do more:

<img width="252" alt="screen shot 2018-05-29 at 19 43 28" src="https://user-images.githubusercontent.com/2011550/40680155-14a32f26-637d-11e8-96db-a0a1a8796604.png">

**Comment by JunBadger** [comment]
Hey @robbiemccorkell 
Past dates should be not selectable if poss.
Noticed that the current date is also knocked back, but this should be full opacity

**Comment by robbiemccorkell** [comment]
Ok I'll try making them non-selectable.

🤦‍♂️  no idea how I didn't notice the current date was faded!

**Comment by JunBadger** [comment]
haha thanks :)

**Comment by robbiemccorkell** [comment]
<img width="504" alt="screen shot 2018-05-30 at 18 14 36" src="https://user-images.githubusercontent.com/2011550/40736306-96665fca-6435-11e8-9f6c-c2258925dbb6.png">

@JunBadger Previous days are now both faded and not selectable in the calendar in the above PR
