### ISSUE TITLE
Category Filter - Copy Change + UI Issue

### ISSUE THREAD

**Issue by JunBadger** [redbadger/pride-london-app#148]
- [x]  Change 'Show me' to 'Showing'

- [x] Change 'All events' to 'All event types'

- ~~Make the chevron CTA 8px margin from the copy (All event types)~~

- [x] Bring baseline of 'All event types' aligned to baseline of 'Showing' (All event types needs to come down a touch - I think @RGBboy noted this in another story)

- [x]  Change 'Add filter' to 'Filter by area, price...'

- [x] 'Select dates' and 'Filter by area, price...' come down to 14px from 16px

- [x] Make vertical divider line between Date/ Filter 1px #ffffff; opacity: 0.4

- [x] After user selects filter options, when they return to Event Listing, feedback still shows 'Filters' + Number of filters selected in 2nd image below:

Left: Pre selection / Right: After selection
![screen shot 2018-04-18 at 14 33 21](https://user-images.githubusercontent.com/14994865/38935265-d9c567ca-4315-11e8-87e7-164f87e48c9f.png)

**Comment by robbiemccorkell** [comment]
@JunBadger for the 3rd point, if we make the chevron CTA 8px from the copy, what should we do when a category is selected? Should the CTA bunch up to the left next to it or stay all the way to the right?

Either way, between the selected and deselected states the CTA will move a little left and right, is this what we want?

<img width="206" alt="screen shot 2018-04-28 at 15 12 07" src="https://user-images.githubusercontent.com/2011550/39397424-d7794836-4af6-11e8-92d6-4a32353ea776.png">
<img width="206" alt="screen shot 2018-04-28 at 15 12 16" src="https://user-images.githubusercontent.com/2011550/39397425-d78d51b4-4af6-11e8-992d-0af7378e5d86.png">

**Comment by robbiemccorkell** [comment]
@JunBadger for the 5th point. "Filter by area, price..." doesn't fit well on narrower devices. Here's an iPhone SE:

<img width="252" alt="screen shot 2018-04-28 at 15 39 50" src="https://user-images.githubusercontent.com/2011550/39397634-86a85146-4afa-11e8-8f53-24ddc6a9c4a0.png">

**Comment by robbiemccorkell** [comment]
Actually now that the font size is down to 14px, it looks like this. Is this ok?

<img width="252" alt="screen shot 2018-04-28 at 15 43 50" src="https://user-images.githubusercontent.com/2011550/39397654-039178f4-4afb-11e8-8d48-829b3680326e.png">

**Comment by JunBadger** [comment]
Hey @robbiemccorkell 

Yes please - the 'Filter by area, price' looks good at 14px (found that it helped users differentiate between categories and other types of filtering).

Good point about the chevron - it would be in a drastically different position if only one of 'health' or 'music' were selected. Could you ignore point 3 please.

**Comment by robbiemccorkell** [comment]
Great, thank you. Will do

**Comment by robbiemccorkell** [comment]
Fixed in #184
