### ISSUE TITLE
Use a smaller font size for category labels (in Event details page) to prevent following label wrapping to new line

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#155]
## Description of issue

Suggestion made on PR #138 :
"I would suggest a smaller font size for category labels as long categories like "Cabaret and Variety" wrap the next label to a new line"

This even affects devices with very wide screen widths like the iPhone 7+ (414px) when the labels are long enough (i.e. "Cabaret and Variety" & "Social and Networking")

## Screenshots

<img src="https://user-images.githubusercontent.com/57560/38824832-71314d38-41a2-11e8-8a67-7d7275e6fe1d.png">

**iPhone 7+**
<img width=400 src="https://user-images.githubusercontent.com/33623842/39045587-2cdc3936-448b-11e8-8c5e-af3623f5e6e6.PNG">

**Comment by RGBboy** [comment]
Blocking for now until #582 is resolved

**Comment by RGBboy** [comment]
Closing as we decided not to decrease the font size due to accessibility problems.
