### ISSUE TITLE
Time of Day filters for events spanning multiple parts of the day

### ISSUE THREAD

**Issue by JunBadger** [redbadger/pride-london-app#171]
Morning (6am - 12pm)
Afternoon (12pm - 6pm)
Evening (6pm til late)

**Comment by robbiemccorkell** [comment]
Also should this just be based off the start time of the event, or should be factor in the end time as well?

**Comment by robbiemccorkell** [comment]
Actually I've looked deeper into it, and our current logic is much more complicated (but actually seems to work quite well).

Morning: start time 00:00 - 11:59
Afternoon: start time before 18:00 and end time after 12:00
Evening: end time after 18:00

These are confusing rules, but it means that if you have an event that starts at 11:00 and ends at 19:00 it will appear in all three filters for morning, afternoon and evening. Which seems correct to me.

**Comment by frigus02** [comment]
Yeah, my idea with the time filter was: when an event is in progress in the morning/evening/afternoon, it should be visible, even when it starts/ends earlier/later.

E.g.: An event, which is from 09:00 to 20:00, should be visible in morning, evening and afternoon.

**Comment by JunBadger** [comment]
Yeah I agree an event spanning several hours would need to be in multiple times of day @robbiemccorkell @frigus02 

In the scenario of an evening event occurs after midnight and finishes before 6, e.g. club, would we need the following logic so it appears as an evening event:
Morning: Start time = 06:00 - 11:59
Afternoon: Start time before 18:00 and end time after 12:00
Evening: End time before 05:59

This might tie in with the Hiding Past Events story so looping you in @stevecottle

**Comment by kristofhamilton** [comment]
This isn't high priority on the event itself but is important for filters.

**Comment by RGBboy** [comment]
Now fixed with #283
