### ISSUE TITLE
iTunes Connect identified issues

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#179]
From iTunes connect on 26.08.2018:

> We identified one or more issues with a recent delivery for your app, "Pride in London". Please correct the following issues, then upload again.
>
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
>
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSLocationWhenInUseUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by RGBboy** [comment]
This is probably coming from the maps module.

**Comment by markholland** [comment]
https://forums.developer.apple.com/thread/101367

**Comment by markholland** [comment]
This was identified as a widepsread issue in iTunes Connect and has since been resolved on their side.
