### ISSUE TITLE
Definition of "Afternoon" will not apply to events lasting until midnight or longer

### ISSUE THREAD

**Issue by Midnite** [redbadger/pride-london-app#183]
## Description of issue

Events that start before 6pm but run until midnight (or longer) will not show up in the `Afternoon` search according to current logic.

## Expected behaviour

You should be able to find events that are on for the whole second part of the day when you search Afternoon events.

## Steps to reproduce

Have event with `startTime: "2018-08-02T14:00:00",` and `endTime: "2018-08-03T00:00:00",` and see if you can find it in the afternoon events list.

**Comment by lani-s** [comment]
Linked with #171
