### ISSUE TITLE
CTAs overlapping with home-line space on iPhone X 

### ISSUE THREAD

**Issue by cellyn-tan** [redbadger/pride-london-app#188]
## Description of issue

On iPhone X, there is a ~34px home-line area at the bottom of every screen. 
CTAs that are at the bottom of the pages will have to accommodate that space so the two do not overlap each other. 

Right now, the issue happens on the following pages: Event details, Donate & Sponsor us.  

<img width="1018" alt="screen shot 2018-04-30 at 10 31 07" src="https://user-images.githubusercontent.com/38290023/39421592-9b912cb4-4c61-11e8-8c9b-b2101355b3d0.png">

## Expected behaviour

On Filter events, there is enough space for the CTA at the bottom. 
<img width="394" alt="screen shot 2018-04-30 at 10 25 24" src="https://user-images.githubusercontent.com/38290023/39421413-d28b8512-4c60-11e8-91d1-2b876026bb58.png">

## OS / Browser / Device model

iPhone X

**Comment by RGBboy** [comment]
I suggest waiting for #186 to be merged before this is fixed. This way we get all of the fixes done in one PR.

**Comment by RGBboy** [comment]
I will address this as part of #271

**Comment by declanslevin** [comment]
Tested as part of #271 and it's fixed
