### ISSUE TITLE
Header text 'Filter Events' is not aligned to the center of screen 

### ISSUE THREAD

**Issue by cellyn-tan** [redbadger/pride-london-app#189]
## Description of issue

Header text is not centred to the screen, slightly edging towards the left. 

<img width="393" alt="screen shot 2018-04-30 at 10 33 30" src="https://user-images.githubusercontent.com/38290023/39421689-11a1a46a-4c62-11e8-9f8e-7aa58c0e4cdb.png">

**Comment by RGBboy** [comment]
I just measured this, and I am pretty sure it is centred. It just looks left aligned because of the cancel text. Can you double check?

**Comment by zoeabryant** [comment]
Seems to be because of the `clear all` button that isn't currently showing on the left 🤔
