### ISSUE TITLE
App crashes when tapping on a Sponsor thumbnail that doesn't have Sponsor URL in Contentful

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#190]
## Description of issue

The app will crash if you tap on a Sponsor that doesn't have a Sponsor URL in Contentful. 
The Sponsor URL field is not marked as required so it possible to publish sponsor content that doesn't have one. 

## Expected behaviour

Either the Sponsor URL field is made a required field or if the sponsor doesn't have a URL the tapping functionality is disabled. 

## Steps to reproduce

- Open the 'Partner with us' page from the 'Support us' tab
- Tap on an event without a Sponsor URL (e.g. Weyland-Yutani)
> App crashes

## OS / Browser / Device model

Galaxy S8
iPhone 7+
iPhone 6

**Comment by frigus02** [comment]
Yeah, the sponsor URL is required. I suggest we fix this by making it required in contentful.

**Comment by declanslevin** [comment]
I changed the Sponsor URL to be required by default in the Content model for Sponsors. I tested and wasn't able to publish a Sponsor without the URL, so closing this
