### ISSUE TITLE
If an event has performances spanning several days the Schedule section gets a bit confusing due to lack of dates

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#199]
## Description of issue

When an event is spanning several days and has a number of performances at different times across those days, it gets a bit confusing in the Schedule section - There are multiple Morning/Afternoon/Evening headers repeated with the different performances listed below. 

This may be an unrealistic scenario for the actual festival, but it might be something that we need to address if there is going to be events of this nature. 

## Expected behaviour

If the performances span several days, the Morning/Afternoon/Evening sections are grouped under their date. 

## Steps to reproduce

- Open the Kim Chi event 
- Scroll to the Schedule section
- Imagine the performances weren't labelled with their date :scream:

## OS / Browser / Device model

Samsung S8
iPhone 7+

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/39475164-233f8514-4d4f-11e8-967a-810b89d5b819.jpg">

**Comment by kristofhamilton** [comment]
There are no events that take place over multiple days.

**Comment by JunBadger** [comment]
This shouldn't be possible if event organisers follow the content editor guide (Recurring event has same schedule / different schedules should be different events on different days)

This is still an issue but is a question of whether we should restrict this behaviour from allowing the error to occur
