### ISSUE TITLE
Display List of Acts: UI Issues

### ISSUE THREAD

**Issue by JunBadger** [redbadger/pride-london-app#203]
- [x] Align the Act to the left hand side of the grid

- [ ] ~~Enforce a character limit of 40 Characters in contentful~~

- [x] Add keyline above and and below the section

- [x] Use 24 hour time 

- [x] Hide last keyline in list

Annotated on designs in Zeplin: zpl://screen?sid=5ae892a4a2eeb781276ed2e4&pid=5a916701f75c524181eebe68

https://app.zeplin.io/project/5a916701f75c524181eebe68/screen/5ae892a4a2eeb781276ed2e4

**Comment by RGBboy** [comment]
This should be done now. @JunBadger feel free to close this if you are happy.
