### ISSUE TITLE
Heart ♡ icon in empty Saved events page copy is too small on Android

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#211]
## Description of issue

The ♡ icon in the copy on the empty Saved events page is appearing a lot smaller than it should on Android. It is doesn't match the size of the ♡ on iOS.

## Expected behaviour

The ♡ icon is the same size on Android as it is on iOS. 

## Steps to reproduce

- Make sure you have no saved events
- Open the Saved tab
> Copy states:
"No favourites yet? Tap the ♡ on any events you like to save them here."
♡ icon is too small. 

## OS / Browser / Device model

Galaxy S8

## Screenshots

**Galaxy S8**
<img width=400 src="https://user-images.githubusercontent.com/33623842/39529127-db6de74c-4e1d-11e8-841d-0ad9ed342eaf.jpg">

**iPhone 7+**
<img width=400 src="https://user-images.githubusercontent.com/33623842/39529207-069023d6-4e1e-11e8-977e-e0f4a1ca13f2.PNG">

**Comment by zoeabryant** [comment]
I've done a bit of investigation and I think this is to do with the pixel density on the android phones. The heart image shown is `24 x 21` pixels, the default image size. Possibly need to increase the size of the base image?
