### ISSUE TITLE
Saved Events page: Make event removal more visible, perhaps with option to undo

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#216]
## Description of issue

When "un-favouriting" an event while viewing the Saved events page, the event card disappears immediately. This presents the potential to accidentally remove an event and not even notice. 
Even if you did notice, it would be irritating to have to go to the Events listing page to find the event again to re-add it. 

## Expected behaviour

Either:
* Collapse to a placeholder that shows 2 buttons, "Undo" and "hide", so if the user didn't intend to remove the event then they could undo it. Perhaps it could just be "Undo" for a few seconds before disappearing. 

* Some kind of animation to show the event being removed so it's more visible.

**Comment by RGBboy** [comment]
@frigus02 just adding you here to keep track of who is working on high priority bugs

**Comment by JunBadger** [comment]
Hi @frigus02 
When looking at PR 5093, it appears as though the final event that you unsave doesn't apply a fade away/ transition - which looks jarring. Can you look into making this consistent with the others?
