### ISSUE TITLE
Tapping on category should open category filter

### ISSUE THREAD

**Issue by JunBadger** [redbadger/pride-london-app#224]
## Description of issue

When user taps on category box, nothing happens

## Expected behaviour

When user taps on either Showing [All event types]
or [name of category filter]
They should be taken to the category filter

![screen shot 2018-05-03 at 17 37 00](https://user-images.githubusercontent.com/14994865/39590508-03f295e2-4ef9-11e8-953e-ebe280019743.png)
![screen shot 2018-05-03 at 17 39 40](https://user-images.githubusercontent.com/14994865/39590521-0cb92fba-4ef9-11e8-8e10-ee2667d535a2.png)

When user scrolls on the category filter this should scroll horizontally and **not** take the user to the category filter

**Comment by lani-s** [comment]
Adding that users should be able to click on the categories on the event pages in order to be taken to the category filtered events listing (after seeing lots of people try to click on them)

**Comment by JunBadger** [comment]
Should this be closed @declanslevin ?

**Comment by declanslevin** [comment]
Yeh this is working now.
