### ISSUE TITLE
Saved events: Empty State design feedback

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#226]
Design amends for sign off of card:
1/
Carriage return after 'any': 
No favourites yet? Tap the ♡ on any [carriage return]
events you like to save them here.

2/
'events' should be singular:
Currently:
No favourites yet? Tap the ♡ on any events you like to save them here.

Should be:
No favourites yet? Tap the ♡ on any event you like to save them here.

3/
Where is the love? too formal
Currently:
Where is the love? 

Should be:
Where's the love?

**Comment by declanslevin** [comment]
Fixed
