### ISSUE TITLE
Can not refresh if there are no events

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#231]
## Description of issue

If contentful has no data, the app gets into a state where the only way to retrieve events is to remove the app and install again. The app just shows the loading text on the event listing screen.

## Expected behaviour

Can refresh events.

## Steps to reproduce

Load the app when contentful has no data. Try to refresh...

## OS / Browser / Device model

Tried on Android, but I am pretty sure this affects all platforms.

**Comment by frigus02** [comment]
Related to #110.

Did we decide how refresh should work in general?

**Comment by RGBboy** [comment]
Will cover in https://trello.com/c/VLDK9GUW/196-refreshing-content
