### ISSUE TITLE
Midnight events appear on wrong day when device is in different timezone

### ISSUE THREAD

**Issue by robbiemccorkell** [redbadger/pride-london-app#247]
## Description of issue

Events occurring at midnight appear in wrong day in event list when device is in a different timezone.

This seems to be an issue with the `date-fns` library applying timezones to processed dates when the `format` function is called. (Similar behaviour has been observed in other functions too).

## Expected behaviour

Events should always show the date and time of the event as it will be in London on the day. Essentially no timezone transformations should be applied.

## Steps to reproduce

Change your device timezone to Toronto, Canada (UTC-4). If using the iOS simulator you will need to do this on your mac system settings.

See that "Midnight recurring dates test event" which occurs at 00:00 on 08 Aug, displays on the event list as 07 Aug

## OS / Browser / Device model

Tested in iOS simulator on iPhone 6

## Screenshots

![screen shot 2018-05-07 at 12 09 41](https://user-images.githubusercontent.com/2011550/39725732-b4cea0d8-5244-11e8-9d9c-dfeaa5ae28a3.png)

<img width="511" alt="screen shot 2018-05-07 at 12 09 49" src="https://user-images.githubusercontent.com/2011550/39725790-dd8c3ce2-5244-11e8-9d34-f651e7a7d418.png">
<img width="483" alt="screen shot 2018-05-07 at 12 09 43" src="https://user-images.githubusercontent.com/2011550/39725791-dda3876c-5244-11e8-8bb7-40d6c6607a57.png">

**Comment by RGBboy** [comment]
Raised https://trello.com/c/wVJtGpjs/197-handling-timezones to try and get a ticket prioritized to address the approach here.
