### ISSUE TITLE
Performance blocks being repeated

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#249]
## Description of issue

It seems that performance times are no longer being correctly grouped by time of day bracket (morning, afternoon, evening). This is the case for the Kim Chi event.

## Expected behaviour

Performances are grouped by singular morning, afternoon, evening sections.

## Steps to reproduce

Go check out Kim Chi on master.

## OS / Browser / Device model

Tested on ios but I imagine this happens on all devices.

![simulator screen shot - iphone 6 - 2018-05-08 at 09 59 56](https://user-images.githubusercontent.com/1566539/39747947-a83cfa24-52a6-11e8-8b69-235de4e738f8.png)

![simulator screen shot - iphone 6 - 2018-05-08 at 10 00 05](https://user-images.githubusercontent.com/1566539/39747948-a856c724-52a6-11e8-8798-8f0d04883fe5.png)

**Comment by RGBboy** [comment]
Ahhhhh. I did not get that. If this is covered by #199 feel free to close this.

**Comment by declanslevin** [comment]
Yeh I think it is the same issue, so closing
