### ISSUE TITLE
Donate page: Possible to submit invalid values (e.g. "1-2-3") in 'Other amount' field

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#255]
## Description of issue

It is possible to submit invalid values in the "Other amount" field. 

For example I was able to submit the following:
`12.34567`
`1-2-3-4-5`
`1.2.3.4.5`
`1.2-3.4-5`
`.` and `-`

## Expected behaviour

The value entered in the "Other amount" field is validated as an actual monetary value for donation.

## Steps to reproduce

- Open the Donate page
- Tap on the "Other amount" field
- Enter a random value
- Tap "Donate" 
> The value is submitted as part of the url, e.g. "https://donate.prideinlondon.org/?amount=1.2.3.4.5"

## OS / Browser / Device model

Galaxy S8

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/39768377-0fba6dd2-52e1-11e8-89b1-097bea88e82e.jpg">
<img width="370" alt="screen shot 2018-05-08 at 16 45 52" src="https://user-images.githubusercontent.com/33623842/39768419-2393759c-52e1-11e8-9cb3-f5217bf05205.png">

**Comment by clmntnbrn** [comment]
This error will be left to the donation platform, as with the minimum amount
