### ISSUE TITLE
Android app crashes when opening the Parade or Support pages

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#268]
## Description of issue

When either the Parade or Support Us pages are opened on Android the app crashes immediately. 

## Expected behaviour

It should never crash :)
<img src="https://media.giphy.com/media/gcn2lEChjIGli/giphy.gif">

## Steps to reproduce

- Open the Parade or Support page in the app

## OS / Browser / Device model

Galaxy S8

**Comment by RGBboy** [comment]
This should be fixed in Beta now with #269 being merged.

**Comment by declanslevin** [comment]
It's no longer crashing for me :)

**Comment by markholland** [comment]
Good reason to get e2e working on android next ;)
