### ISSUE TITLE
Lock app down to be portrait only

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#272]
## Description of issue

Describe the error in as much detail as possible.

## Expected behaviour

If it's a functional issue, describe what would have been the correct behaviour.

## Steps to reproduce

List the exact steps you took to arrive at the issue.

## OS / Browser / Device model

List all the devices and browsers effected, with specific version numbers.

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by frigus02** [comment]
I don't think we need to do a whole lot to make the app work correctly in landscape. Do we want to have a quick look at what's required to leave landscape enabled on Saturday?

**Comment by matt-paul** [comment]
Hey @frigus02, we discussed this in a meeting a little earlier.  Think @lani-s will be giving you a shout about it.

**Comment by lani-s** [comment]
@frigus02 we discussed that the work involved in getting landscape view to look okay from a uxd perspective is too much effort right now for a rare and ill-defined accessibility use case. We can revisit if and when we have the time?
