### ISSUE TITLE
Donate urls

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#285]
## Description of issue

Donate urls are not currently live (there is a dependency on the main site build) - if this does not get resolved in time for launch we will need to look at other ways of linking to set donation amounts (e.g. paypal?)

## Expected behaviour

That you click a link, and are taken to a page which exists: https://trello.com/c/XmsDjp8f/82-donate

**Comment by RGBboy** [comment]
All done now 👍
