### ISSUE TITLE
Quote on Donate page does not fit on small iPhone SE screen

### ISSUE THREAD

**Issue by frigus02** [redbadger/pride-london-app#286]
## Description of issue

The quote on the Donate page should have 1 line break:

> "It's the first time I feel
> accepted in a big group."

The iPhone SE screen is too small for the second line, making it break:

![image](https://user-images.githubusercontent.com/3579251/39957717-7361392c-55ef-11e8-89f4-41e9c5bdfcdf.png)

## Expected behaviour

???

## Steps to reproduce

Open Donate page on iPhone SE.

## OS / Browser / Device model

* iPhone SE

**Comment by RGBboy** [comment]
I think this may happen in a number of places. I wonder if a better approach would be to specify these as a single string, then when we render split on the space so that it breaks naturally to a new line. This will have a bit of design impact, so it would be good to chat with UXD about it.
