### ISSUE TITLE
Privacy policy url

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#287]
## Description of issue

Waiting for Pride to provide this - blocking while we wait

**Comment by lani-s** [comment]
https://prideinlondon.org/privacy

**Comment by lani-s** [comment]
Don't have permissions to update myself.. soz

**Comment by markholland** [comment]
So on Android looks like you can only update the live store listing. So will leave this open and should be part of when we update the rest of the listing.

**Comment by markholland** [comment]
on iOS changes aren't made to the listing until you release a new version, The new privacy policy URL is set and will show when we go to prod.

**Comment by RGBboy** [comment]
This has now been added to all the right places.
