### ISSUE TITLE
Too much space below status bar (2 SaveAreaViews)

### ISSUE THREAD

**Issue by frigus02** [redbadger/pride-london-app#290]
## Description of issue

There is too much space between status bar and headers on iPhones.

![image](https://user-images.githubusercontent.com/3579251/39959500-6bfa7296-560a-11e8-97d2-ffd25e4dff4a.png)

The SaveAreaView is applied twice.

## Expected behaviour

No extra space.

## Steps to reproduce

Go to any page except home on an iPhone.

## OS / Browser / Device model

iPhones

**Comment by RGBboy** [comment]
Hmmmm, I am pretty sure I addressed this in the status bar PR. I'm guessing something got taken out in a conflict. I will take a look.
