### ISSUE TITLE
Contentful data not being loaded in latest Android beta

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#300]
## Description of issue

Event and sponsor data isn't being loaded in the latest Android beta (v1.0.7 5343) - the Home, Events, Saved and Sponsor pages aren't loading correctly. The Parade and Support us pages appear correctly, which leads me to think it is specific to Contentful data that the app isn't able to load. 

I tested the previous versions (v1.0.7 5301) and it was working as expected. 

## Expected behaviour

Contentful data is loaded correctly in the app. 

## Steps to reproduce

- Open the app 👍 

## OS / Browser / Device model

Physical Galaxy S8

BrowserStack Galaxy S7
BrowserStack Galaxy S8

## Screenshots

**Home Page**
<img width=400 src="https://user-images.githubusercontent.com/33623842/40049412-a340716e-582c-11e8-9b7d-45d1741a29c6.jpg">

**Events Listing Page**
<img width=400 src="https://user-images.githubusercontent.com/33623842/40049493-d223308e-582c-11e8-8f0b-6e6063d8aa03.jpg">

**Saved Events**
<img width=400 src="https://user-images.githubusercontent.com/33623842/40049466-bfabb390-582c-11e8-9197-910065ef6967.jpg">

**Sponsor Page**
<img width=400 src="https://user-images.githubusercontent.com/33623842/40049488-cc41673a-582c-11e8-9821-812d56cfd598.jpg">

**Comment by markholland** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **org.prideinlondon.festival.MainActivity**](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5afa9c7858df150019309f31?event_id=5afae93fefdbf900186d0144&i=gh&m=li)

**Comment by markholland** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **org.prideinlondon.festival.MainActivity**](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5afa9c7858df150019309f31?event_id=5afae93fefdbf900186d0144&i=gh&m=fx)
