### ISSUE TITLE
Duplicate recurring events

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#305]
## Description of issue

The first occurrence of a recurring event is shown twice on the event listing screen

## Expected behaviour

Only one is shown.

## Steps to reproduce

Open the app, load the latest data, navigate to event listing, scroll to Friday 13th July see Recurring dates test event twice for the same day and time. 

## OS / Browser / Device model

All

## Screenshots

<img width="559" alt="screen shot 2018-05-15 at 17 40 53" src="https://user-images.githubusercontent.com/1566539/40071032-a16d7ffe-5867-11e8-85f9-40bffbee22d4.png">

**Comment by robbiemccorkell** [comment]
Well that's crap. Don't know how I missed that, sorry

**Comment by robbiemccorkell** [comment]
I've looked into this, and it's simply because the start date of the event, and the first recurrence are the same day. So it's kind of correct.

But I could always add a filter to make sure you can't have a recurrence on the same day as the start date
