### ISSUE TITLE
Staged category filters do not clear after pressing Android hardware back button

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#307]
## Description of issue

Using the hardware back button on Android when staging changes to the categories filter does not clear the staging state. 

## Expected behaviour

Navigating back into the categories filter after pressing hardware back should show the current applied categories.

## Steps to reproduce

Navigate to the events screen.
Navigate to the category filter screen.
Select a couple of categories.
Press hardware back.
Notice no filters have been applied.
Navigate back to the category filter screen.
Notice categories are selected.

## OS / Browser / Device model

Android, any.

## Screenshots

<img width="286" alt="screen shot 2018-05-16 at 09 25 59" src="https://user-images.githubusercontent.com/1566539/40106038-9875b13e-58ec-11e8-9688-49493700d9f3.png">

<img width="287" alt="screen shot 2018-05-16 at 09 26 21" src="https://user-images.githubusercontent.com/1566539/40106043-9b478eaa-58ec-11e8-9ed0-53930b58b4db.png">

**Comment by declanslevin** [comment]
This can be closed as the filter navigation has been changed so that pressing back applies the filters.
