### ISSUE TITLE
Accessibility iOS : When a button is toggled with Voiceover enabled, it reads out both the previous state and the new state labels

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#322]
## Description of issue

When double-tapping on a button to toggle its state with Voiceover enabled on iOS, it reads out both the previous and new state of the button, which is quite confusing as it isn't clear which state the button is now in.

## Expected behaviour

When double-tapping to toggle a button, only the new state label of the button is read out. 

## Steps to reproduce

- Enable VoiceOver
- Open the Category filter
- Tap on "Cabaret and Variety"
> It reads out "Cabaret and Variety, Checkbox, Empty"
- Double-tap on "Cabaret and Variety"
> It reads out "Cabaret and Variety, Checkbox, Empty, Cabaret and Variety, Checkbox, Selected"

It should probably just read out "Selected, Cabaret and Variety" when the label is double-tapped to align with the iOS checkbox accessibility behaviour. 

## OS / Browser / Device model

iPhone 7+

**Comment by RGBboy** [comment]
@declan could you please find out what the default iOS behaviour is when toggling checkboxes on iOS (perhaps on the iOS settings screen). I would expect this to read the same.

**Comment by declanslevin** [comment]
I didn't find a check box in the same style as we are using but I did find options that are 'checkable' in the following menu: 
Settings > General > Accessibility > Home Button

When checked, Voiceover reads out the following: "Selected, Slow" (Slow was the option selected) so it doesn't match the behaviour in the app.

**Comment by frigus02** [comment]
The ASOS app seems to be a good example. It says:

* When the item is not selected: <label>, button
* When the item it not selected and you double tap: selected, <label>
* When the item is selected: selected, <label>, button
* When the item is selected and you double tap: <label>
