### ISSUE TITLE
Updating: Attempting manual refresh without a network connection results in the app getting stuck in the currently refreshing state

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#326]
## Description of issue

Manually refreshing with Flight Mode enabled results in the refresh icon appearing and spinning endlessly. Once in this state, after disabling Flight Mode the events page never completes the refresh. It is then not possible to trigger another manual refresh, even after switching tabs and returning to the Events page. 

## Expected behaviour

When there is no network connection, the app recognises this and stops attempting to refresh with a message along the lines of "Check your Network Connection". 

If the network connection kicks back in before the app gives up on refreshing, it should complete the refresh as expected. Further refreshes should then be possible.  

## Steps to reproduce

- Open the app to the Events page
- Enable Flight mode
- Manually refresh the Events page by pulling down and wait
> The refresh icon will endlessly spin
- Disable Flight mode
> The refresh icon will continue to endlessly spin
- Attempt to refresh again
> Manual refresh no longer works. 
On Android, switching tab then coming back to Events page gets rid of the refresh icon, but nothing happens when you try to pulldown and refresh again. 
On iOS, refresh icon persists despite switching tab and returning to Events page. 

## OS / Browser / Device model

Galaxy S8
iPhone 7+

**Comment by RGBboy** [comment]
This is probably related to not handling the failure of the load. Should be relatively easy to fix. Just need to reset the CMS Loading state to not loading if the request fails.
