### ISSUE TITLE
Poor Connection: App doesn't look great when opened with a bad internet connection

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#327]
## Description of issue

Using "Network Link Conditioner" to simulate a poor internet connection (1mbps bandwidth, 10% packet loss, 500ms delay), when opening the app in a fresh state (no previously loaded Contentful data) the Home Page looks broken and empty. The Events page is blank too. 

## Expected behaviour

It might be worth creating some kind of placeholder state with messaging to let the user know that their poor connection is causing content loading to be slow. 

## Steps to reproduce

- Freshly install the app on iPhone, **don't open it yet**
- Disable the iPhone's Wi-Fi and Mobile Data
- Add "Network Link Conditioner" through Xcode > Open Developer Tools > More Developer Tools > Additional Tools for Xcode (version)
- Connect iPhone through USB
- Enable Internet Sharing (System Preferences > Sharing) to the iPhone
- Open Network Link Conditioner
- Set the Profile to "Very Bad Network" and switch it ON
- Open the app on the iPhone
> Takes a very long time to load any content

## OS / Browser / Device model

iPhone 7+

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/40318076-5732a99c-5d1b-11e8-8083-8f0edae13503.PNG">

**Comment by charypar** [comment]
Since #320, the effect of a poor network should be the splash screen staying on for a long time, rather than a broken screen.

Normally we'd just show locally cached data and then try refreshing in the background, so this is only on the first launch

We probably do need a nicer screen for the initial load on a slow connection.

**Comment by frigus02** [comment]
Yes, unless it's the first launch and there is no network at all. In this case the splash screen currently stays there forever. I think in this case we want a special error screen with a retry button.

**Comment by clmntnbrn** [comment]
![poor connection](https://user-images.githubusercontent.com/12392657/40966141-8e67fa7e-68a7-11e8-8e87-eaf0df5918c1.jpg)

**Comment by charypar** [comment]
Can we make that heart tappable and play the animation? As a little easter egg to play with while you're waiting for the network to work?

**Comment by clmntnbrn** [comment]
Ooo that would be nice! Although people wouldn't know that behaviour existed if they hadn't seen the app before

**Comment by clmntnbrn** [comment]
![poor connection top grey](https://user-images.githubusercontent.com/12392657/41027942-372ca880-6970-11e8-9c1d-ce742c672975.jpg)

**Comment by lani-s** [comment]
Closing as it duplicates the trello ticket: https://trello.com/c/VzYYoXoC/215-behaviour-when-theres-poor-internet-connection
