### ISSUE TITLE
Event details page: Remove the end date when events run past midnight 

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#330]
## Description of issue

The Event details page currently shows a date range when events run past midnight.

<img width=400 src="https://user-images.githubusercontent.com/33623842/40416240-b1dc5f78-5e74-11e8-9418-0f1db5d3c590.jpg">

## Expected behaviour

Only show the start date as events aren't intended to run over several days and it should be obvious to users that some events will run into the early hours of the following day.

**Comment by declanslevin** [comment]
This still needs a final decision, possibly awaiting some further user testing, so please hold off working on this without UXD approval.

**Comment by clmntnbrn** [comment]
@declanslevin UXD is happy to just have the date when the event starts, and remove the end date
