### ISSUE TITLE
Homescreen not visible if there's an issue with Featured Events data

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#335]
## Description of issue

The home screen in prod is not visible if there is an issue with Contentful data. Was fixed by accessing the featured events in the CMS and seeing an event linked which was problematic. Removed said event and added another one and the home screen reappeared in refresh. 

## Expected behaviour

That the home screen doesn't crash if there is an issue with one event in the featured events listing. 

Concerned that once all events are past this will be a recurring issue. 

## Steps to reproduce

Open the app. Oh! There's nothing there, it's just a sad grey expanse. 

Tab through and other tabs appear as expected. 

Go into Contentful and look at featured events to find the culprit. 

## OS / Browser / Device model

List all the devices and browsers effected, with specific version numbers.

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by RGBboy** [comment]
This will be related to having FilteredEvents with essentially no events. Related to the event data changes that I would like to make.
