### ISSUE TITLE
Filtering: Add a "Reset all filters" button to the Events page

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#340]
## Description of issue

Currently if you have filter(s) applied it requires a minimum of 2 taps to reset to the default state. If you have multiple filters enabled then it's even more, requiring you to open each filter individually to reset them to the default state. 

## Expected behaviour

When filter(s) are set a "Reset all filters" button appears on the Events page.

**Comment by clmntnbrn** [comment]
![event listing reset filters](https://user-images.githubusercontent.com/12392657/40920352-2dde0e94-6804-11e8-8289-4825fcc8e795.jpg)
Display Reset all filters once one has been set - font size to be the same as 'Select dates' etc

**Comment by jonyardley** [comment]
I will pick this up today :)

**Comment by robbiemccorkell** [comment]
If the header is growing, does that mean the list area will be super tiny on an iPhone 4?

**Comment by robbiemccorkell** [comment]
If so we might be able to mitigate that in the future by hiding the header like in #66

**Comment by clmntnbrn** [comment]
yep @robbiemccorkell I reckon that's a good shout - only the date remains sticky. Let's add the reset button and I'll talk to @stevecottle about whether we should do the rest

**Comment by charypar** [comment]
I appreciate I'm a bit too late to the party, but would this look better as a thin sticky banner saying something like "Filters applied" at the top of the list with a ✖️icon on the right? Like one of the date headers, but a different colour, maybe the green we use for the number badge. 

This look like a bit of an afterthought and will make a lot of the UI move in an odd way when tapped.
