### ISSUE TITLE
TypeError in org.prideinlondon.festival.MainActivity

### ISSUE THREAD

**Issue by markholland** [redbadger/pride-london-app#347]
## Error in Pride in London 2018 app

**TypeError** in **org.prideinlondon.festival.MainActivity**
undefined is not a function (evaluating 'r()')

[View on Bugsnag](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5b10073d7ce000001868136c?event_id=5b10073d7ce000001868136b&i=gh&m=ci)

## Stacktrace

    src/screens/EventsScreen/component.js:92 - onRefresh

[View full stacktrace](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5b10073d7ce000001868136c?event_id=5b10073d7ce000001868136b&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by declanslevin** [comment]
Fixed by #353
