### ISSUE TITLE
TypeError in org.prideinlondon.festival.MainActivity

### ISSUE THREAD

**Issue by markholland** [redbadger/pride-london-app#349]
## Error in Pride in London 2018 app

**TypeError** in **org.prideinlondon.festival.MainActivity**
undefined is not a function (evaluating 'r()')

[View on Bugsnag](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5b111066a16fec00193b37ba?event_id=5b111066a16fec00193b37b9&i=gh&m=ci)

## Stacktrace

    src/screens/DonateScreen/accessibilityLabel.android.js:33 - onRefresh

[View full stacktrace](https://app.bugsnag.com/pride-in-london/pride-in-london-2018-app/errors/5b111066a16fec00193b37ba?event_id=5b111066a16fec00193b37b9&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by markholland** [comment]
This is the same bug as #348

**Comment by markholland** [comment]
Caused when manual refreshing the events list

**Comment by declanslevin** [comment]
Fixed by #353
