### ISSUE TITLE
E2E tests for all screens

### ISSUE THREAD

**Issue by RGBboy** [redbadger/pride-london-app#374]
For regression it would be great if we can add tests for our main screens in the app. Currently we only have tests for navigating to the first level tab.

It may be a good idea to try some user flows along with testing getting to each screen. E.g. navigate to an event, refresh content, applying filters, save an event etc.

**Screens:**

- Home - **Tested**
  - Featured Events
- Events - **Tested**
  - Category Filter
  - Date Filter
  - Filter? Filter (area, price etc)
  - Event Details
- Parade - **Tested**
- Saved - **Tested**
- Support - **Tested**
  - Donate
  - Sponsor (Partner)

E2E tests are written here: https://github.com/redbadger/pride-london-app/blob/master/e2e/firstTest.spec.js

**Comment by markholland** [comment]
Also feel free to restructure in any way. Would be good to get at least one example of each type of test we'd like then we can fill out as we have time.

**Comment by RGBboy** [comment]
Related to #302

**Comment by RGBboy** [comment]
Closing this as we now have tests for navigating to all screens. We are still missing tests for filtering etc, but can add these as part of #302
