### ISSUE TITLE
Calendar Past Dates: Reduce opacity of past date numbers to 25/30%

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#377]
## Description of issue

Requested on the [Whole app - Not showing Past Events](https://trello.com/c/JVwbl10D/154-whole-app-not-showing-past-events) trello ticket:

> Can we reduce the opacity of the past (and not selectable) days to 25-30%? Grab one of us to pair when you're doing it ;)

**Comment by RGBboy** [comment]
Can someone check the latest beta after #378 was merged? I think this might have been done.

**Comment by RGBboy** [comment]
Closing this as this will be addressed in #419
