### ISSUE TITLE
Past Events: Expired events aren't being removed when switching tabs

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#379]
## Description of issue

Switching to a non-events tab (Parade/Donate) and back to events is no longer removing expired events from the listing. 

This was working previously, I re-tested in a build from Fri 1st June (build 6205) and it works there, but in the latest build (6545, 4th June) it has stopped working. 

## Expected behaviour

When an event expires and you switch to the Parade/Donate tabs and back to the Events listing, the expired event is gone. 

## Steps to reproduce

- Set "Hide Past Event Test" to expire in a couple of minutes
- Refresh the Events page so that the event is visible
- Wait for the event end time to pass
- Switch to the Parade tab then back to the Events page
> The event is still there

## OS / Browser / Device model

Galaxy S8
iPhone 7+

**Comment by RGBboy** [comment]
Note: we have added functionality to only refresh the event every half an hour. So the reproduction steps will need to be performed at that point in time.

**Comment by RGBboy** [comment]
@declanslevin does my comment above mean we need to test in a different way?

**Comment by declanslevin** [comment]
Ah that will explain why it only worked once when this first came up as an issue XD 
I don't think we need to test it differently - just that it's a little harder now, having to wait for 30 mins between tests.

**Comment by RGBboy** [comment]
Can we close this? I can show you it working locally if that helps.
