### ISSUE TITLE
Parade Map: Map position is only reset when switching to the "Stages" page and back

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#386]
## Description of issue

It is possible to reset the Parade map's position by swapping to the "Stages" page then back to the map, but this doesn't work when switching to any other page (i.e. Events).

This is a relatively minor issue - but if I was to be a little pedantic I would say this doesn't meet the acceptance criteria for [View Parade route on map](https://trello.com/c/vwkpzgNw/69-june-parade-day-view-parade-route-on-map):

> When user navigates away from the Parade Section and returns, the default location is set back to the Parade Route

## Expected behaviour

Switching to any other page in the app and back to the parade map resets it to the default position/scale (showing the parade route).

## Steps to reproduce

- Open the Parade Tab
- Modify the map position
- Switch to the Events tab
- Switch back to Parade tab
> Map hasn't been reset

## OS / Browser / Device model

Galaxy S8
iPhone 7+

**Comment by stevecottle** [comment]
It would be helpful if we could get this one resolved.

**Comment by abinocoe** [comment]
This has now been resolved in latest version of #362

**Comment by declanslevin** [comment]
fixed
