### ISSUE TITLE
Parade Map: When zoomed in, parade start/end points produce visual artefacts

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#387]
## Description of issue

On iOS, using Apple Maps, when zooming in on a point for the parade route, a visual artefact appears near the point.
This may just be a quirk of Apple maps that we can't do anything about, but it looks unpolished and would be good to fix if possible when more work is done on the maps page.

## Expected behaviour

No visual artefacts appear when changing the zoom level of the parade map. 

## Steps to reproduce

- Open the parade map page
- Zoom in on the B point on the map
> A visual artefact appears next to the point

## OS / Browser / Device model

Doesn't affect Google Maps on Android

iPhone 7+ iOS 10.3.1

## Screenshots

<img width=400 src="https://user-images.githubusercontent.com/33623842/41039201-a3272bf8-6990-11e8-9e65-35b1cd054d02.PNG">

**Comment by markholland** [comment]
Weird, I’m not seeing this exact issue but it is true that if you zoom in and then pan the line will get wider and then re render to thin again. So likely both quirks with the library

**Comment by RGBboy** [comment]
The icons have now changed. Closing, however if other artefacts are found happy if it gets reopened.
