### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#391]
## Description of issue

Here is a list of design issues to provide consistency with other components in the app:

- [ ] Typography of the map/stages component should be consistent with that of the filter events component: 
  - [ ]  Typeface
  - [ ]  Typeface size
  - [ ]  Typeface weight 
  - [ ]  Active state
  - [ ]  Inactive state

- [ ]  Style of the map/stages component should be consistent with that of the filter events component:
  - [ ]  Height
  - [ ]  Colour

- [ ]  Green line of the map/stages component should be consistent with that of the tab bar:
  - [ ]  Animate in from right to left on focusing to the Parade section
  - [ ]  Animate between Map and Stages tab when focussing between the two
  - [ ]  Weight (height)
  - [ ]  Colour

- [ ]  Vertical keyline of the map/stages component should be consistent with that of the filter events component:
  - [ ]  Weight (width)
  - [ ]  Colour

**Comment by RGBboy** [comment]
I think this is done. @abinocoe can you confirm?
