### ISSUE TITLE
Map Placeholder: Image doesn't resize when font size is changed

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#401]
## Description of issue

The placeholder image for the "Check back soon" card on the parade route map doesn't resize nicely when the font size is changed.

Probably not much of an issue considering the placeholder is temporary, but would be nice to fix. 

## Expected behaviour

When the font size is increased/decreased the placeholder resizes accordingly.

## Steps to reproduce

- Increase/decrease the font size
- Restart the app if necessary
- Open the Parade tab and view the map
> Placeholder image hasn't resized along with the font

## OS / Browser / Device model

Galaxy S8
iPhone 7+

## Screenshots

**Default font size:**
![20180608_162820](https://user-images.githubusercontent.com/33623842/41167096-da3ae62a-6b39-11e8-9e61-9f4de8fe080d.jpg)

**Android increased font:**
![20180608_162902](https://user-images.githubusercontent.com/33623842/41167120-ecd7a49e-6b39-11e8-92e3-99b23766ce2c.jpg)

**iOS increased font:**
![fullsizerender 6](https://user-images.githubusercontent.com/33623842/41167181-166ae974-6b3a-11e8-9882-368a98a21b20.jpg)

**Android decreased font:**
![20180608_162846](https://user-images.githubusercontent.com/33623842/41167209-2e7ad704-6b3a-11e8-80a1-b8d4a398ba33.jpg)

**iOS decreased font:**
![fullsizerender 5](https://user-images.githubusercontent.com/33623842/41167225-3a6a85a0-6b3a-11e8-86ef-408ee57cf088.jpg)

**Comment by RGBboy** [comment]
This has now changed to the event card and no longer applies.
