### ISSUE TITLE
Parade Map: Crash when interacting rapidly with Google map

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#402]
## Description of issue

When interacting rapidly and erratically with the parade map, it crashes. Only reproduced on Android (Google Maps). 

Crash report: 
[org.prideinlondon.festival.beta_issue_3_crash_5B1A9427018100014D23EA58265F5A1A_DNE_0_v2.txt](https://github.com/redbadger/pride-london-app/files/2085046/org.prideinlondon.festival.beta_issue_3_crash_5B1A9427018100014D23EA58265F5A1A_DNE_0_v2.txt)

## Expected behaviour

It shouldn't crash no matter how quickly it is interacted with.

## Steps to reproduce

- Open the Parade map
- Rapidly zoom in and out of the map repeatedly
- Try changing the position and rotation as well
> It will crash at some point

Come get me if you're having trouble reproducing. 

## OS / Browser / Device model

Galaxy S8
Galaxy Note Edge

**Comment by markholland** [comment]
https://stackoverflow.com/questions/50691006/is-there-a-workaround-fix-to-these-google-maps-v2-stackoverflowerror-crashes

**Comment by RGBboy** [comment]
Closing as tracking in #457
