### ISSUE TITLE
Play Store parade screenshot

### ISSUE THREAD

**Issue by clmntnbrn** [redbadger/pride-london-app#433]
## Description of issue

This screenshot needs to replace the current one

## Screenshots

![playstoreassets5](https://user-images.githubusercontent.com/12392657/41345032-7a3f6722-6efa-11e8-81b6-0ab3184e3edd.jpg)

**Comment by markholland** [comment]
I'll do this now! 👍

**Comment by clmntnbrn** [comment]
💪
