### ISSUE TITLE
Can't build locally for android simulator

### ISSUE THREAD

**Issue by robbiemccorkell** [redbadger/pride-london-app#44]
Since this commit https://github.com/redbadger/pride-london-app/commit/0d61bf95bb69e2d79d5ad391d872197e2d600e8a `yarn run-android` stopped working. It throws the error `pride-london-app/android/.gradle/gradle.properties (No such file or directory)`.

I'm assuming the line `props.load(new FileInputStream(file("../.gradle/gradle.properties")))` is the culprit here. But I don't know enough about the android build system to know what it should be, or how to skip this step during local development. 

@markholland any ideas?

**Comment by markholland** [comment]
Hmm, well you wouldn’t want to skip this locally because then you wouldn’t be able to run on a device as it would be an unsigned build. Strange that run-android makes a release build rather than a debug. Will have to look closer.

**Comment by robbiemccorkell** [comment]
Thanks. I've been playing around and commenting out some of the build signing stuff definitely makes the simulator build work.

I see what you mean. You'd think a local build wouldn't try and run release config anyway

**Comment by markholland** [comment]
If commenting out the file load works then this should be suficcient for now. https://github.com/redbadger/pride-london-app/pull/45

**Comment by robbiemccorkell** [comment]
Ok thanks for the above PR. That solves one problem, but I've found another one...

It seems that the `productFlavors` block is confusing local simulator builds.

When I run `yarn run-android` I get the message at the end of the build process:
```
Starting: Intent { cmp=com.pridelondonapp/.MainActivity }
Error type 3
Error: Activity class {com.pridelondonapp/com.pridelondonapp.MainActivity} does not exist.
```

This was actually silently failing, the only reason I didn't notice it was because I already had a binary on my simulator that the app could run in. I only noticed something was wrong when some of my recent changes involving binary updates (fonts and maps), weren't working. Took me ages to realise my binary wasn't updating.

If I comment out the whole `productFlavors` block in `android/app/build.gradle` then the build works again.

I'm not sure why this block is causing the issue. But presumably a local build thinks it is one of these product flavors and is ending up with a messed up classpath or something.

**Comment by markholland** [comment]
This should tide you over `run-android --variant=alphaDebug`. It will still have the error but the app will be installed.

Not sure when I'll have enough time to tackle a proper fix.

**Comment by robbiemccorkell** [comment]
Huh, interesting I didn't know about the variant flag. So what's the problem do you think? Does the `run-android` command actually do an alpha or beta build by default, and it's picking up build config that clashes?

What does `alphaDebug` do, put it on a productFlavor that we don't have configuration for?

**Comment by robbiemccorkell** [comment]
Hmm,

Unfortunately it looks like adding `--variant=alphaDebug` triggers `./gradlew installAlphaDebug`, but the same error occurs and the app doesn't install

**Comment by markholland** [comment]
`alphaDebug` means build using the `alpha` flavor with the `debug` build type. Our Alpha CI builds are `assembleAlphaRelease` as another example.

**Comment by robbiemccorkell** [comment]
Weird. And by the way, to test it properly I had to delete the app from the simulator device first. Otherwise I didn't get the full error, just some undescriptive warning and the new build wouldn't be installed. 

That's what caught me out over the last few days. It looked like it was loading the latest binary, but it was actually just failing and opening what was already installed.

**Comment by markholland** [comment]
I think I was wrong to jump to flavors being the issue just because they're the most recent change. The run-android task runs the gradle task `debugAndroidTest` which shouldn't be affected by flavors at all.

**Comment by robbiemccorkell** [comment]
It does seem to be flavours related though, because if I comment out the whole `productFlavors ` block, the problem goes away.

**Comment by markholland** [comment]
`mkdir android/app/src/main/assets`

`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

`yarn run-android --variant=alphaDebug`

**Comment by markholland** [comment]
And regarding not launching the app this is definitely flavors and doesn’t have a work around for Android in general...

**Comment by frigus02** [comment]
I'm trying to work on this. Is it fine to update our Gradle version and Android Gradle plugin to the latest version?

**Comment by markholland** [comment]
You can try, dependencies may fail if they haven’t been updated as well but there are work arounds in that case.
