### ISSUE TITLE
Add Made in partnership graphic

### ISSUE THREAD

**Issue by clmntnbrn** [redbadger/pride-london-app#450]
## Description of issue

Please add the partnership graphic to the home screen

## Expected behaviour

It should look like this:
![partnership example](https://user-images.githubusercontent.com/12392657/41419551-39b65828-6fea-11e8-8e46-eb8bad92f4cd.jpg)

Zeplin link: [zpl://project?pid=5a916701f75c524181eebe68](url)

**Comment by RGBboy** [comment]
Just adding Tracy to this as she has picked it up from Trello

**Comment by RGBboy** [comment]
Closing as this is now in master 👍
