### ISSUE TITLE
Google Maps (and the app) crashes on Android after zooming in/out

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#457]
## Description of issue

It seems that Google maps interactions (zoom in/out) causes the app to crash

## Expected behaviour

The app doesn't crash if you zoom in and out. 

## Steps to reproduce

Open the parade tab and interact with the map a bit - zoom in and out etc and notice it crashes. 

## OS / Browser / Device model

Tested on Samsung 8 and Pixel 2 (probably applies to all android)

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by lani-s** [comment]
https://github.com/redbadger/pride-london-app/issues/453

**Comment by RGBboy** [comment]
I may have found a fix

**Comment by RGBboy** [comment]
#473 may fix this

**Comment by RGBboy** [comment]
This is now in master. Once released we should no longer see bugsnag errors like these:

#418
#446
#453
#458
#459
#460
#461
#462
#463
#467
#468
#472

**Comment by RGBboy** [comment]
In production for Android and no longer crashing 👍
