### ISSUE TITLE
map location icon: apple icon is used on android

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#464]
## Description of issue

'take me to my location' icon on android uses apple icon (arrow) instead of android icon (target)

## Expected behaviour

Android target icon should be used on android devices

## Steps to reproduce

On Android, go to parade route
Look top right
Observe apple arrow icon instead of android target icon

## OS / Browser / Device model

only tested on my Pixel

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

![screenshot_20180618-132051](https://user-images.githubusercontent.com/11883999/41535551-9d8656ce-72fa-11e8-87a6-ed09a6930715.png)

**Comment by abinocoe** [comment]
So it was decided to use the functionality that we're using for iOS to go to current location, and while that was happening, consensus was that the iOS button was nicer/behaved better. I am however more than happy to change this to an android button, but it would mean getting assets from somewhere 😬

**Comment by JunBadger** [comment]
Hi @abinocoe Can we please use the Android icon? Think it might be better to keep the respective icon for each map application

**Comment by frigus02** [comment]
The default Android button is not as nice. It doesn't have an active state. In addition we have limited control over its functionality. Would be great we could get custom assets, that match the Android default icon, though.

**Comment by JunBadger** [comment]
Cool - yeah let's do that... I'll hunt for an Android-ish icon @frigus02

**Comment by JunBadger** [comment]
Downloadable assets for Android Current Location in Zep:
zpl.io/awY1LgD 
zpl.io/ad7k4wK

**Comment by abinocoe** [comment]
thank you @JunBadger

**Comment by abinocoe** [comment]
@JunBadger is it possible to get those icons grouped with the white background circle?

**Comment by JunBadger** [comment]
Cool, all done @abinocoe

**Comment by lani-s** [comment]
Downgraded this to medium as we have some higher priority issues (like the map crashing the app)
