### ISSUE TITLE
Current Location: Map iOS

### ISSUE THREAD

**Issue by JunBadger** [redbadger/pride-london-app#469]
- Current Location icon needs to be aligned to the grid (flush to the outside margin of 8px or 16px depending on device width).
- Ideally Current Location sits in the top right with compass appearing underneath it. Currently the behaviour is that the space for compass is left empty until user reorientates map. (This is lower priority)

![img_9572](https://user-images.githubusercontent.com/14994865/41549995-6333c536-731f-11e8-9ca1-28d389eae550.JPG)

**Comment by frigus02** [comment]
There is no way to change the compass location. Now that I think about it, we may be able to move the location button up/down depending on if the compass is visible or not.

We noticed when comparing this with other apps on Android (Maps, Uber, ...), that the default position on Android for the "my location" button is on the bottom right. When there is something like our "come back soon" card, the location button is then just above the card.

**Comment by JunBadger** [comment]
^ Sitting above right to the card might be a better solution then the current solution (with space for compass missing)
What are your thoughts @stevecottle 
Shall we switch to the default?

**Comment by frigus02** [comment]
Just to be clear, that seems to be the default on Android.

In Apple Maps the button is on the top right. Maybe we can have a look at other apps on iOS.

**Comment by RGBboy** [comment]
@JunBadger Is this still an issue on master? If not would you mind closing?

**Comment by JunBadger** [comment]
Sorry @RGBboy - I should have closed this since I paired with @abinocoe 
We actually agreed on a location but think it has since been moved as per this current story

Is it possible to bring it to the position we set?

**Comment by RGBboy** [comment]
What is currently in master is what will be released for 2.0.2:

<img width="416" alt="screen shot 2018-07-03 at 11 28 09" src="https://user-images.githubusercontent.com/1566539/42214725-3a3bb9fe-7eb4-11e8-9f1c-bd4a23f16cf8.png">

**Comment by RGBboy** [comment]
This is what it currently looks like with the compass:

<img width="416" alt="screen shot 2018-07-03 at 11 30 56" src="https://user-images.githubusercontent.com/1566539/42215176-8ea533d4-7eb5-11e8-8bd3-874b87c15d28.png">

We would like the right hand side of the navigate to location to align with the right hand side of the compass. The fact that the widths differ is acceptable so that the hit area is big enough.
