### ISSUE TITLE
Animated splash screen implementation

### ISSUE THREAD

**Issue by charypar** [redbadger/pride-london-app#480]
These are implementation notes to build https://trello.com/c/FTZWoZUe/180-welcome-loading-page

![image](https://user-images.githubusercontent.com/1517854/41809745-929e9bd8-76ea-11e8-8b73-e06e984aece5.png)

## Behaviour

When I open the app I should see the design above, when the app is ready, the heart animates and screen slides up to reveal the home page content.

## General approach

The purpose of a splash screen is to pretend the application launches faster than it actually does. The goal is still to get the user to content as soon as possible.

In our case this means hiding the splash screen as soon as we have content to display, which is when we've either fetched data from the CMS (first launch) or loaded cached data from disk (subsequent launches).

In order to do the welcome screen in React Native (and enable more behaviour as described in https://trello.com/c/VzYYoXoC/215-behaviour-when-theres-poor-internet-connection and #327), there  generally three steps to this, but the process and capabilities differ on the platforms.

### iOS

1. App starts launching: The system finds the launch screen interface file in `Base.lproj/LaunchScreen.xib` and displays it, while starting the app in the background. This is **splash screen no. 1**, defined in an interface builder file and built in XCode Interface Builder. It can contain any kind of layout, but for our purposes it should probably contain two images:
    - The "Discover Plan ❤️" text essentially centred on screen
    - The Pride logo a fixed distance from the bottom
2. App finishes launching, we put the react native root view in the window and instruct `react-native-splash-screen` (RNSS) to show the splashscreen, which uses the same launch screen interface file. This is **splash screen no. 2**. 

The nice thing is both screens are defined by the same source on iOS.

### Android

This is a little more complicated.

1. App starts launching. In `AndroidManifest.xml` we declare the main activity and set its `android:theme` (temporarily) to `@style/SplashTheme`, this is defined in `res/values/styles.xml` and shows `@drawable/background_splash` in `res/drawable/background_splash` - **splash screen no. 1**. Similar to iOS we can put two images on it:
    - The "Discover Plan ❤️" text essentially centred on screen
    - The Pride logo a fixed distance from the bottom

    However, this screen is a [drawable](https://developer.android.com/guide/topics/resources/drawable-resource), so we are somewhat limited in our options, but should be able to replicate the overall look using a [layer list](https://developer.android.com/guide/topics/resources/drawable-resource#LayerList) with centered bitmap items to avoid fluid scaling, something along the lines of this example from the linked page:

```xml
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
      <bitmap android:src="@drawable/android_red"
        android:gravity="center" />
    </item>
    <item android:top="10dp" android:left="10dp">
      <bitmap android:src="@drawable/android_green"
        android:gravity="center" />
    </item>
    <item android:top="20dp" android:left="20dp">
      <bitmap android:src="@drawable/android_blue"
        android:gravity="center" />
    </item>
</layer-list>
```

2. The app launches, we call `SplashScreen.show` and the RNSS takes over. This however displays a different splash screen defined in `app/src/main/res/layout/launch_screen.xml` - **splash screen no. 2**. This one is a [layout](https://developer.android.com/guide/topics/resources/layout-resource), but we should be able to re-use the drawable from step 1 in it. 

### Common

3. React Native loads and renders our app. At this point we render the same screen - **splash screen no. 3** with React Native. As it loads, we hide the native splash screen using a call to RNSS and wait for the data to load from cache or CMS (and do any other activity that has to finish to show the users content). 
4. Once data loads, we start the heart animation and hide the screen by sliding it away (or similar).

## Implementation stages

It seems the easiest to do this back to front - start with splash screen no. 3, as that is our goal state. 

Once that is done, we can hopefully set up the splash screens no. 1 and 2 to mimic the initial state of no. 3. The easiest way to get the assets is probably to simply screenshot the finished splash screen no. 3.

We can hide the splash screen no. 3 while this is in progress with a feature flag in order to deliver this in smaller individual PRs.

## Assets required

* The light on dark pride logo, high res. We will need to make many variations of this for the three iOS and one thousand and seventy nine Android versions.
* The layout of the screen in Zeplin (for measurements) and some instruction on how the layout should adapt to different screen sizes (i.e. aspect ratios) - my guess is logo sticks to the bottom, the text and heart stay above the centre point of the screen.
* The heart animation (It _should_ be possible to reuse the existing one on dark, but need to confirm)

**Comment by RGBboy** [comment]
Closing as this is now implemented
