### ISSUE TITLE
Stages on Map: Pin doesn't centre to screen when tapped on iOS

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#492]
## Description of issue

When I tap on a stage pin the pin remains in its current position

## Expected behaviour

When I tap on a stage pin I'd expect the pin to move to the center of the screen / frame

## Steps to reproduce

Navigate to Parade > Map
Drag screen to make a stage pin off-center
Tap on stage pin
Stage pin remains in position

## OS / Browser / Device model

Jun's iPhone X

## Screenshots

none

**Comment by RGBboy** [comment]
This is an iOS problem. Android exhibits the correct behaviour.
