### ISSUE TITLE
Loading screen: status bar not visible

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#494]
## Description of issue

When I start the app and see the loading screen, the phone's status bar is not visible

## Expected behaviour

I expect to see the status bar at all times while using the app

## Steps to reproduce

Open the app
Observe the status bar the top is not visible while the loading screen is being displsayed

## OS / Browser / Device model

Pixel

## Screenshots

![screenshot_20180628-103053](https://user-images.githubusercontent.com/11883999/42029628-1d0cc35e-7ac8-11e8-958c-71a45484c93d.jpg)

**Comment by serdemli** [comment]
@stevecottle I couldn't replicate it with the new loading screen. 
Is this still valid after the update to loading screen?

**Comment by stevecottle** [comment]
Closing issue as this screen has been superseded by the purple screen which doesn't have this issue.
