### ISSUE TITLE
Map: Doesn't re-center when I navigate back to map

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#496]
## Description of issue

When I move the map position and then navigate away from the map. If I navigate back to the map, the map stays in the same position as it was left

## Expected behaviour

I'd expect the parade route to have been centred on the screen / frame

## Steps to reproduce

Navigate to Parade > Map
Move the map so the parade route is no longer centred
Navigate to eg Stages tab
Navigate back to Map tab
Observe the parade route has not re-centred 

## OS / Browser / Device model

Pixel

## Screenshots

None

**Comment by RGBboy** [comment]
This should be fixed after #408 is merged. Zooming the longitude to a very small value seems to fix this.

**Comment by RGBboy** [comment]
Seems we had a regression here. Is now fixed with #540
