### ISSUE TITLE
Map: My location button takes me to my location twice when I press it twice

### ISSUE THREAD

**Issue by frigus02** [redbadger/pride-london-app#501]
## Description of issue

On Android:

- Go to parade map and click on location button.
- Before it takes you your location, click it again.
- Wait until it takes you to your location and move away.
- It will now take you to your location again.

Possibile cause:

Every click on the "my location" button seems to trigger a call to the location service. On Android it can take a few seconds to receive the location. Once it gets it, it moves the map. In between you can still move the map to anywhere you want, though.

## Expected behaviour

- It should only ask the location service once. When I click the button again and it didn't receive something from the last call, don't call again.
- If the users moves the map while we retrieve the location, we should not go to the users location anymore??

## OS / Browser / Device model

Most visible on Android.

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by RGBboy** [comment]
I will be looking into this along with #503 and #502.
