### ISSUE TITLE
Android (6.0.1) You can spam the location button on the map.

### ISSUE THREAD

**Issue by AndreiDanielIonescu** [redbadger/pride-london-app#502]
## Description of issue
You can spam the location button on the map.
Describe the error in as much detail as possible.
If you receive the message for not being able to pick up the location, you can actually spam the button a lot so the message will be flickering on your screen
## Expected behaviour

If it's a functional issue, describe what would have been the correct behaviour.
 Is it possible to put a timeout on the button, a delay to wait for a response?
## Steps to reproduce
 Go to map.
 Spam the location button.

List the exact steps you took to arrive at the issue.
 The message for not being able to locate you should have a delay and not flicker 

## OS / Browser / Device model
 Android 6.0.1

List all the devices and browsers effected, with specific version numbers.

## Screenshots

If it's a visual bug, please provide screenshots or screen captures.

**Comment by frigus02** [comment]
Sounds like the same as #501

**Comment by RGBboy** [comment]
I will be looking into this along with #501 and #503.
