### ISSUE TITLE
Get a list of all the offending images

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#532]
## Description of issue

Big is beautiful. But in this case, is also causing a big performance lag on Android. 

We've implemented restrictions on image resolution but a number of the existing images in Contentful are over that. To help the content editors can we get a list of the offending images? Is it possible to only get the images for events which are today/in the future? 

## Image spec

Individual Events detail picture (header image on individual event page)
Image provided should be landscape, and will be cropped to a ratio of 5:3
Width = minimum 500px & maximum 1500px
Height = minimum 280 & maximum 1500px
Ideal size <1MB

Events List picture (image shown in event listing)
Image provided will be cropped square
Width & Height = minimum 200px, maximum 750px
Ideal size <700KB

**Comment by RGBboy** [comment]
I relaxed the constraint a bit to 1600 for the Individual Events detail picture and 800 for the Events List picture. As of 03-07-2018@12:00 this is the list of images that exceed that size. I have passed this to Kristof via Slack.

[image-size-exceeded.txt](https://github.com/redbadger/pride-london-app/files/2159145/image-size-exceeded.txt)

**Comment by RGBboy** [comment]
Closing as these have been provided to Kristof
