### ISSUE TITLE
Loading screen transitions twice

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#545]
## Description of issue

On the loading page, once the heart animates the page transitions to the homepage. once on the home page for a second, the loading page transitions again.

## Expected behaviour

On the loading page, once the heart animates the page transitions to the homepage once and no more.

## Steps to reproduce

Install the latest version, open the app for the first time, observe the loading screen transitions twice.

## OS / Browser / Device model

Pixel

## Screenshots

https://photos.app.goo.gl/ifXAtDhVHPa7tB1Q6

**Comment by RGBboy** [comment]
@stevecottle This may have been fixed by #551 which is now in master (Beta). Would you mind retesting and closing if you can not trigger it again.

**Comment by stevecottle** [comment]
Downloaded latest version of app and can't reproduce issue so closing.

cc @RGBboy
