### ISSUE TITLE
Events listing: pull to refresh triggers loading screen

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#547]
## Description of issue

When I pull to refresh on the events listing page the loading screen it triggered.

## Expected behaviour

When I pull to refresh on the events listing page, default pull to refresh behaviour is displayed (loading icon appears, spins and disappears)

## Steps to reproduce

Navigate to Events tab
Pull doen screen
Loading icon appears and spins
Loading screen appears and transitions away

## OS / Browser / Device model

Pixekl

## Screenshots

None

**Comment by RGBboy** [comment]
Same on iOS. Eeeeeek!
