### ISSUE TITLE
Map: Focus to location after navigating away from page

### ISSUE THREAD

**Issue by stevecottle** [redbadger/pride-london-app#548]
## Description of issue

When I tap the location icon, it focusses to my location. When I navigate elsewhere in the app eg Saved, then back to the Map, my location remains focussed.

## Expected behaviour

When I tap the location icon, it focusses to my location. When I navigate elsewhere in the app eg Saved, then back to the Map, parade area should be focussed.

## Steps to reproduce

Go to parade > Map
Tap location icon
Tap Saved in tab bar
Tap Parade in tab bar
Observe my location is focussed

## OS / Browser / Device model

Pixel

## Screenshots

None

**Comment by RGBboy** [comment]
#540 should fix this. Just waiting for it to build and I will double check
