### ISSUE TITLE
No internet loading screen crash

### ISSUE THREAD

**Issue by serdemli** [redbadger/pride-london-app#556]
## Description of issue
The loading screen for no internet sometimes crashes the app on iPhone 6s Beta build. 

## Expected behaviour
It should display the no internet wifi screen and show messaging along with CTA to try again.

## Steps to reproduce
Delete app.
Download latest Beta build. 
Put iPhone on airplane mode, disconnect from wifi.
Launch the app - notice the initial loading screen appears.
After a while 10-15 sec or longer, the app crashes. 

**Note:** Crashing is sporadic. It happens about 50% of the time.

## OS / Browser / Device model
iPhone 6s, version 11.2.5

**Comment by Lily418** [comment]
Have replicated this crash, seems to not occur when connected to debugger. Attached is the crash log which I'm going to have a look through now.
[PrideLondonApp  03-07-2018, 16-45.crash.zip](https://github.com/redbadger/pride-london-app/files/2160084/PrideLondonApp.03-07-2018.16-45.crash.zip)

**Comment by Lily418** [comment]
I think this crash occurs because the Splash Screen is not hiding quickly enough so the app is being killed. This would explain why it doesn't get killed when running through Xcode and the crash is sporadic because network latency can vary. Will continue investigating tomorrow.
