### ISSUE TITLE
ReasonML?

### ISSUE THREAD

**Issue by jonyardley** [redbadger/pride-london-app#6]
Whilst away with Stu we talked about potentially having pride be a good place to introduce ReasonML to the RB arsenal proper. I would be interested to get other peoples opinions on this?

https://github.com/reasonml-community/bs-react-native

Things to bear in mind:
- ReasonML itself is quite new but gaining support and traction quickly.
- Use with React Native is newer still.
- Do the software design advantages out-way the potential teething problems?
- A bit of a learning curve for us?
- More of a learning curve for anyone who might be contributing via open-source?

**Comment by markholland** [comment]
For future reference:

https://github.com/nickzuber/add-reason

Cli tool to interop ReasonML with an existing js project
