### ISSUE TITLE
Event price - requires price even when event is free

### ISSUE THREAD

**Issue by lani-s** [redbadger/pride-london-app#83]
see screenshot attached - please close is this is not a bug and simply something which needs to be covered in the content editor guide

<img width="1280" alt="screen shot 2018-03-27 at 16 45 40" src="https://user-images.githubusercontent.com/7224477/37978649-6367bf1c-31de-11e8-8a05-6c9ff1a8a4c8.png">

**Comment by lani-s** [comment]
This is a mandatory field in Contentful so closing and ensuring it is added to the content guide

**Comment by robbiemccorkell** [comment]
We could also just get rid of the `isFree` flag and figure it out from the required values
