### ISSUE TITLE
Tapping on contact details should open phone/email app

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#93]
To improve ease of contacting event organisers, I think when you visit an Event page and tap on the phone/email in the contact information section it should automatically open the appropriate app with the contact detail selected prepopulated ready for the user to quickly get in touch. 

Currently they are raw text that you can't even highlight to copy/paste. (Even this ability would be a big improvement)

An example event with contact details is "Evil Morty" (4th July)

**Comment by RGBboy** [comment]
Should be fixed in #150
