### ISSUE TITLE
Images aren't appearing when linked in Event description 

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#96]
Tested with: 
Physical Samsung Galaxy S8
Simulator iPhone X

When an image is hosted on Contentful and added to the Event description, it is not being loaded when the Event page is opened. 
Images hosted externally are appearing as expected on Android, but not on a Simulated iPhone (still haven't succeeded at getting a build for iOS):

Android:
<img width="409" alt="Android screen capture" src=https://user-images.githubusercontent.com/33623842/38370028-ff10f1aa-38e0-11e8-8177-5d87bf8d489c.jpg>
(In this example the image at the top is from Google, the purple box with ? is where the Contentful image should appear)

iOS Simulator:
<img width="409" alt="screenshot at apr 05 14-59-56" src="https://user-images.githubusercontent.com/33623842/38370513-2ccc1466-38e2-11e8-9d35-d59025bfeaf0.png">

The example event is the one with the car-crash collection of emojis and symbols for a name, date is 20th April.

**Comment by robbiemccorkell** [comment]
Out of interest were the images tested on an http or https url? iOS really hates loading assets that aren't https. Hopefully there's a way around it

**Comment by declanslevin** [comment]
It was a http url, after changing it to https, it is loading the image on iOS

**Comment by markholland** [comment]
You can add a domain whitelist to the info.plist https://cocoacasts.com/how-to-add-app-transport-security-exception-domains

**Comment by RGBboy** [comment]
Interestingly this works on my simulator. Has this been fixed inadvertently?

**Comment by declanslevin** [comment]
It isn't working on a physical iOS device (iPhone 7+)

**Comment by RGBboy** [comment]
Fixed in #267
