### ISSUE TITLE
Location information pushed off the event widget in the listings page when font size is increased

### ISSUE THREAD

**Issue by declanslevin** [redbadger/pride-london-app#97]
Tested on:
Samsung Galaxy S8 (Android 8.0)
iPhone 7+ (iOS 10.3.1)

**Increased font size**
Android (set to maximum size in Accessibility settings):
<img width=400 src="https://user-images.githubusercontent.com/33623842/38376958-af6aa1b2-38f1-11e8-8502-c75c07a86327.jpg">

**RESOLVED**
~~**Long titles**
Events with (albeit ridiculously) long titles will push the location information off the event tile so it is no longer immediately visible:
Android:~~
<img width=400 src="https://user-images.githubusercontent.com/33623842/38375092-3dee0334-38ed-11e8-98f9-38f89b043490.jpg">
~~iOS:~~
<img width=400 src="https://user-images.githubusercontent.com/33623842/38375102-452381f6-38ed-11e8-9201-d886e6e858cc.PNG">

**Comment by JunBadger** [comment]
When user increases their default text size:
- use the following max- font sizes as per: https://github.com/redbadger/pride-london-app/issues/128 
- Event name remains truncated at 2 lines
- Event location will truncate at 2 lines
- Image will responsively fill the available height
- We assume the bottom padding of 12px will ensure the card increases in height responsively to the content resizing (but can pair with a dev to see how this works)

<img width="770" alt="screen shot 2018-04-16 at 11 38 55" src="https://user-images.githubusercontent.com/14994865/38804604-d64f9f36-416a-11e8-8069-7168e10678eb.png">

zpl.io/bAvvZKn

**Comment by declanslevin** [comment]
The long title issue has been resolved as the event title text is now restricted to 2 lines which leaves space for the location on the tile. 

It is still an issue when font size is increased however.

**Comment by zoeabryant** [comment]
@dclanslevin does https://github.com/redbadger/pride-london-app/pull/225 resolve this issue?
